// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail.proto

package mail

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Mail struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	To                   string               `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	From                 string               `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Sent                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=sent,proto3" json:"sent,omitempty"`
	Read                 bool                 `protobuf:"varint,5,opt,name=read,proto3" json:"read,omitempty"`
	Body                 string               `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Subject              string               `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Mail) Reset()         { *m = Mail{} }
func (m *Mail) String() string { return proto.CompactTextString(m) }
func (*Mail) ProtoMessage()    {}
func (*Mail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0}
}

func (m *Mail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mail.Unmarshal(m, b)
}
func (m *Mail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mail.Marshal(b, m, deterministic)
}
func (m *Mail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mail.Merge(m, src)
}
func (m *Mail) XXX_Size() int {
	return xxx_messageInfo_Mail.Size(m)
}
func (m *Mail) XXX_DiscardUnknown() {
	xxx_messageInfo_Mail.DiscardUnknown(m)
}

var xxx_messageInfo_Mail proto.InternalMessageInfo

func (m *Mail) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Mail) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Mail) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Mail) GetSent() *timestamp.Timestamp {
	if m != nil {
		return m.Sent
	}
	return nil
}

func (m *Mail) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *Mail) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Mail) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type MailID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailID) Reset()         { *m = MailID{} }
func (m *MailID) String() string { return proto.CompactTextString(m) }
func (*MailID) ProtoMessage()    {}
func (*MailID) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{1}
}

func (m *MailID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailID.Unmarshal(m, b)
}
func (m *MailID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailID.Marshal(b, m, deterministic)
}
func (m *MailID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailID.Merge(m, src)
}
func (m *MailID) XXX_Size() int {
	return xxx_messageInfo_MailID.Size(m)
}
func (m *MailID) XXX_DiscardUnknown() {
	xxx_messageInfo_MailID.DiscardUnknown(m)
}

var xxx_messageInfo_MailID proto.InternalMessageInfo

func (m *MailID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MailID) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetMailRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	All                  bool     `protobuf:"varint,3,opt,name=all,proto3" json:"all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMailRequest) Reset()         { *m = GetMailRequest{} }
func (m *GetMailRequest) String() string { return proto.CompactTextString(m) }
func (*GetMailRequest) ProtoMessage()    {}
func (*GetMailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{2}
}

func (m *GetMailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMailRequest.Unmarshal(m, b)
}
func (m *GetMailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMailRequest.Marshal(b, m, deterministic)
}
func (m *GetMailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMailRequest.Merge(m, src)
}
func (m *GetMailRequest) XXX_Size() int {
	return xxx_messageInfo_GetMailRequest.Size(m)
}
func (m *GetMailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMailRequest proto.InternalMessageInfo

func (m *GetMailRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetMailRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetMailRequest) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

type GetMailResponse struct {
	Mail                 []*Mail  `protobuf:"bytes,1,rep,name=mail,proto3" json:"mail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMailResponse) Reset()         { *m = GetMailResponse{} }
func (m *GetMailResponse) String() string { return proto.CompactTextString(m) }
func (*GetMailResponse) ProtoMessage()    {}
func (*GetMailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{3}
}

func (m *GetMailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMailResponse.Unmarshal(m, b)
}
func (m *GetMailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMailResponse.Marshal(b, m, deterministic)
}
func (m *GetMailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMailResponse.Merge(m, src)
}
func (m *GetMailResponse) XXX_Size() int {
	return xxx_messageInfo_GetMailResponse.Size(m)
}
func (m *GetMailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMailResponse proto.InternalMessageInfo

func (m *GetMailResponse) GetMail() []*Mail {
	if m != nil {
		return m.Mail
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Mail)(nil), "mail.Mail")
	proto.RegisterType((*MailID)(nil), "mail.MailID")
	proto.RegisterType((*GetMailRequest)(nil), "mail.GetMailRequest")
	proto.RegisterType((*GetMailResponse)(nil), "mail.GetMailResponse")
	proto.RegisterType((*Empty)(nil), "mail.Empty")
}

func init() { proto.RegisterFile("mail.proto", fileDescriptor_7cda5f053e74676b) }

var fileDescriptor_7cda5f053e74676b = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x4e, 0x83, 0x40,
	0x14, 0xec, 0x52, 0x5a, 0xf0, 0xd5, 0x54, 0xb3, 0xd1, 0x64, 0xc3, 0x41, 0xc9, 0xc6, 0x18, 0xbc,
	0xd0, 0x58, 0x3d, 0xf8, 0x01, 0x35, 0xa6, 0x87, 0x7a, 0x40, 0xfd, 0x00, 0x90, 0xd7, 0x06, 0x05,
	0x16, 0x61, 0x39, 0xf4, 0x9f, 0xfc, 0x2d, 0xff, 0xc3, 0xec, 0x6e, 0x5b, 0x8b, 0x1e, 0xbc, 0xcd,
	0x1b, 0xe6, 0xcd, 0xcc, 0xb2, 0x0b, 0x50, 0xc4, 0x59, 0x1e, 0x56, 0xb5, 0x90, 0x82, 0xda, 0x0a,
	0x7b, 0xe7, 0x2b, 0x21, 0x56, 0x39, 0x4e, 0x34, 0x97, 0xb4, 0xcb, 0x89, 0xcc, 0x0a, 0x6c, 0x64,
	0x5c, 0x54, 0x46, 0xc6, 0x3f, 0x09, 0xd8, 0x8b, 0x38, 0xcb, 0xe9, 0x18, 0xac, 0x2c, 0x65, 0xc4,
	0x27, 0xc1, 0x41, 0x64, 0x65, 0xa9, 0x9a, 0xa5, 0x60, 0x96, 0x99, 0xa5, 0xa0, 0x14, 0xec, 0x65,
	0x2d, 0x0a, 0xd6, 0xd7, 0x8c, 0xc6, 0x34, 0x04, 0xbb, 0xc1, 0x52, 0x32, 0xdb, 0x27, 0xc1, 0x68,
	0xea, 0x85, 0x26, 0x2c, 0xdc, 0x86, 0x85, 0xcf, 0xdb, 0xb0, 0x48, 0xeb, 0x94, 0x47, 0x8d, 0x71,
	0xca, 0x06, 0x3e, 0x09, 0xdc, 0x48, 0x63, 0xc5, 0x25, 0x22, 0x5d, 0xb3, 0xa1, 0xf1, 0x55, 0x98,
	0x32, 0x70, 0x9a, 0x36, 0x79, 0xc3, 0x57, 0xc9, 0x1c, 0x4d, 0x6f, 0x47, 0x7e, 0x0b, 0x43, 0xd5,
	0x76, 0x3e, 0xfb, 0xd3, 0xd7, 0x03, 0xb7, 0x6d, 0xb0, 0x2e, 0xe3, 0x02, 0x37, 0xad, 0x77, 0x33,
	0x7f, 0x84, 0xf1, 0x03, 0x4a, 0xb5, 0x18, 0xe1, 0x47, 0x8b, 0x8d, 0xec, 0xa8, 0x49, 0x57, 0xbd,
	0x71, 0xb6, 0x76, 0xce, 0xc7, 0xd0, 0x8f, 0xf3, 0x5c, 0x1f, 0xdc, 0x8d, 0x14, 0xe4, 0xd7, 0x70,
	0xb4, 0xf3, 0x6b, 0x2a, 0x51, 0x36, 0x48, 0xcf, 0x40, 0xff, 0x70, 0x46, 0xfc, 0x7e, 0x30, 0x9a,
	0x42, 0xa8, 0x6f, 0x42, 0x2b, 0x34, 0xcf, 0x1d, 0x18, 0xdc, 0x17, 0x95, 0x5c, 0x4f, 0xbf, 0x88,
	0x39, 0x02, 0xd6, 0xf4, 0x0e, 0x9c, 0x8d, 0x0d, 0x3d, 0x31, 0x0b, 0xdd, 0x96, 0xde, 0xe9, 0x2f,
	0xd6, 0x64, 0xf1, 0x1e, 0xbd, 0x00, 0xf7, 0x09, 0xcb, 0x54, 0xaf, 0xee, 0x65, 0x79, 0x7b, 0x98,
	0xf7, 0xe8, 0x15, 0xc0, 0x0c, 0x73, 0x94, 0xa8, 0x75, 0x87, 0x3f, 0xdf, 0xe6, 0x33, 0x6f, 0x64,
	0x26, 0xdd, 0x89, 0xf7, 0xe8, 0x25, 0xb8, 0x8b, 0xb8, 0x7e, 0x8f, 0xd4, 0x8d, 0x74, 0x85, 0x5d,
	0xcb, 0x00, 0x40, 0xe9, 0x5e, 0xca, 0xfa, 0x1f, 0x65, 0x32, 0xd4, 0xaf, 0xe0, 0xe6, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x0d, 0xb7, 0x9d, 0x21, 0x94, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MailerClient is the client API for Mailer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailerClient interface {
	GetMail(ctx context.Context, in *GetMailRequest, opts ...grpc.CallOption) (*GetMailResponse, error)
	SendMail(ctx context.Context, in *Mail, opts ...grpc.CallOption) (*Mail, error)
	DeleteMail(ctx context.Context, in *MailID, opts ...grpc.CallOption) (*Empty, error)
	MarkRead(ctx context.Context, in *MailID, opts ...grpc.CallOption) (*Mail, error)
	MarkUnread(ctx context.Context, in *MailID, opts ...grpc.CallOption) (*Mail, error)
}

type mailerClient struct {
	cc *grpc.ClientConn
}

func NewMailerClient(cc *grpc.ClientConn) MailerClient {
	return &mailerClient{cc}
}

func (c *mailerClient) GetMail(ctx context.Context, in *GetMailRequest, opts ...grpc.CallOption) (*GetMailResponse, error) {
	out := new(GetMailResponse)
	err := c.cc.Invoke(ctx, "/mail.Mailer/GetMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailerClient) SendMail(ctx context.Context, in *Mail, opts ...grpc.CallOption) (*Mail, error) {
	out := new(Mail)
	err := c.cc.Invoke(ctx, "/mail.Mailer/SendMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailerClient) DeleteMail(ctx context.Context, in *MailID, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/mail.Mailer/DeleteMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailerClient) MarkRead(ctx context.Context, in *MailID, opts ...grpc.CallOption) (*Mail, error) {
	out := new(Mail)
	err := c.cc.Invoke(ctx, "/mail.Mailer/MarkRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailerClient) MarkUnread(ctx context.Context, in *MailID, opts ...grpc.CallOption) (*Mail, error) {
	out := new(Mail)
	err := c.cc.Invoke(ctx, "/mail.Mailer/MarkUnread", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailerServer is the server API for Mailer service.
type MailerServer interface {
	GetMail(context.Context, *GetMailRequest) (*GetMailResponse, error)
	SendMail(context.Context, *Mail) (*Mail, error)
	DeleteMail(context.Context, *MailID) (*Empty, error)
	MarkRead(context.Context, *MailID) (*Mail, error)
	MarkUnread(context.Context, *MailID) (*Mail, error)
}

func RegisterMailerServer(s *grpc.Server, srv MailerServer) {
	s.RegisterService(&_Mailer_serviceDesc, srv)
}

func _Mailer_GetMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailerServer).GetMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.Mailer/GetMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailerServer).GetMail(ctx, req.(*GetMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mailer_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailerServer).SendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.Mailer/SendMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailerServer).SendMail(ctx, req.(*Mail))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mailer_DeleteMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailerServer).DeleteMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.Mailer/DeleteMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailerServer).DeleteMail(ctx, req.(*MailID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mailer_MarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailerServer).MarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.Mailer/MarkRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailerServer).MarkRead(ctx, req.(*MailID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mailer_MarkUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailerServer).MarkUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.Mailer/MarkUnread",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailerServer).MarkUnread(ctx, req.(*MailID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mailer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mail.Mailer",
	HandlerType: (*MailerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMail",
			Handler:    _Mailer_GetMail_Handler,
		},
		{
			MethodName: "SendMail",
			Handler:    _Mailer_SendMail_Handler,
		},
		{
			MethodName: "DeleteMail",
			Handler:    _Mailer_DeleteMail_Handler,
		},
		{
			MethodName: "MarkRead",
			Handler:    _Mailer_MarkRead_Handler,
		},
		{
			MethodName: "MarkUnread",
			Handler:    _Mailer_MarkUnread_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail.proto",
}
